config/routes.rb
MEbGDP::Application.routes.draw do

  get "tips/rwrh"
  get "tips/gamma"
  get "tips/lambda"
  get "tips/eta"
  get "tips/net_selection"
  get "tips/phenome_net"

  get "predictions/parameter"
  get "predictions/predict"
  get "predictions/pollAllResults"
  get "predictions/showOverlappedResults"
  get "predictions/showAllResults"
  get "predictions/downloadResults"

  get "diseases/search"
  
  get "genes/search"
  get "genes/compare_phenotype"

  root :to => 'pages#home'
  match '/about', :to => 'pages#about'
  match '/contact', :to => 'pages#contact'
  match '/help', :to => 'pages#help'
  
  get 'pages/autocomplete_disease_disease_name'

end

app/models/prediction.rb
class Prediction
  include ActiveModel::Validations  #Extend the model to allow validation and client side validation
  include ActiveModel::Conversion
  extend ActiveModel::Naming
  
  attr_accessor :omim_id, :top_results, :lambda, :eta, :gamma, :network
  
  #Validation criteria for prediction parameter
  validates :omim_id, :presence => true, :numericality => { :greater_than => 0, :only_integer => true }
  validates :top_results, :presence => true, :numericality => { :greater_than => 0, :less_than => 2000, :only_integer => true }
  validates :lambda, :presence => true, :numericality => { :greater_than => 0, :less_than => 1 }
  validates :eta, :presence => true, :numericality => { :greater_than => 0, :less_than => 1 }
  validates :gamma, :presence => true, :numericality => { :greater_than => 0, :less_than => 1 }
  validate :validate_networks #Custom validator for prediction method
  
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end
  
  def persisted?
    false
  end
  
  def validate_networks
    @allowed_network = ["getSemanPrior","getSemanNPrior","getPPIPrior","getPPINPrior"]  #Allowed keywords
    if network.nil? # At least one method should be selected
      errors.add(:network, "Select at least 1 network!")
    else
      network.each do |network_name|  #Check if all submitted method name is valid
        unless @allowed_network.include?(network_name)
          errors.add(:network, "Please use valid method name!")
          break
        end
      end
    end
  end
  
  
end

app/controllers/predictions_controller.rb
class PredictionsController < ApplicationController
  require Rails.root.join('app', 'tasks', 'RwrhJob.rb')
  require 'zip/zip'
  require 'open-uri'
  
  OMIM_API_KEY = '30C52EDBCFC6F856381C6FC7C10B852FCB36CA3B' #Put your omim api key here
  OMIM_API_URL = 'http://api.omim.org/api/entry'  #OMIM API main url
  OMIM_INCLUDED_SECTIONS = 'include=text:cytogenetics&include=text:description&include=text:molecularGenetics'  #Required sections of OMIM entry
  
  def parameter #Render to prediction oarameter panel, need return disease info
    @disease = Disease.find_by_omim_id(params[:omim_id])
    @prediction = Prediction.new  #Create an empty prediction parameter object, defined in models/prediction
    @title = "Prediction Panel"
    render :layout => "noLayout"
  end

  def predict #Prediction action
    @title = "Prediction Results"
    @parameter = Prediction.new(params[:prediction])  #Create the prediction parameter object with user query
    if @parameter.valid?  #Validation defined in models/prediction
       @task_id = Time.new.to_time.to_i
       task_dir = "task_temp/#{@task_id}" #Create temp task folder for intermediate process
       Dir.mkdir(task_dir)  #Record prediction parameter in the log file
       writeLogFile(params[:prediction][:omim_id],
                    params[:prediction][:top_results],params[:prediction][:lambda],
                    params[:prediction][:gamma],params[:prediction][:eta],
                    params[:prediction][:network], @task_id)
                    
       @omim_id = params[:prediction][:omim_id]
       #Put the prediction task into the task queue
       Delayed::Job.enqueue RwrhJob.new(params[:prediction][:omim_id],
                                        params[:prediction][:top_results],params[:prediction][:lambda],
                                        params[:prediction][:gamma],params[:prediction][:eta],
                                        params[:prediction][:network], @task_id)
    else
      @disease = Disease.find_by_omim_id(params[:prediction][:omim_id])
      redirect_to :controller => 'diseases', :action => 'search', :keyword => params[:prediction][:omim_id]
    end
  end
  
  def pollAllResults  #Load all results from the task file (for 1st time display)
    @task_id = params[:task_id]
    @omim_id = params[:omim_id]
    task_folder = Rails.root.join('task_temp',@task_id)
    if File.exists?("#{task_folder}/finish")  #Test if the task is finished
      @linkage_interval = getLinkageInterval(@omim_id)  #Load the linkage interval for compare to the genes
      File.delete("#{task_folder}/finish")
      writeOverlappedResultsFile(task_folder)
      @disease = Disease.find_by_omim_id(@omim_id)
      @results = loadAllResultFiles(task_folder)  #Load result files
      @overlapped_results = loadResultFile(task_folder, "overlapped.txt")
    end
  end
  
  def showOverlappedResults #The action is only used to render showOverlapped Results script, need no action
    
  end
  
  def showAllResults  #Load all results from the task file (for displaying back from overalpped results)
   
  end
  
  def downloadResults #Download files to user browser
    task_id = params[:task_id]
    task_folder = Rails.root.join('task_temp',task_id)
    zipfile_name = generateZipFile(task_id) #Zip the result files
    send_file zipfile_name, :type=>"application/zip" 
  end
  
  private
  
  def writeLogFile(omim_id, top_results, lambda, gamma, eta, network, task_id)
    task_dir = "task_temp/#{task_id}"
    logFile_dir = Rails.root.join(task_dir,'log.log')
    logFile = File.new(logFile_dir,"w")
    logFile.write("#{Time.new}\n")
    logFile.write("===========================\n\n")
    logFile.write("OMIM Entry: #{omim_id}\n")
    logFile.write("Top Results: #{top_results}\n")
    logFile.write("Lambda: #{lambda}\n")
    logFile.write("Gamma: #{gamma}\n")
    logFile.write("Eta: #{eta}\n")
    logFile.close
  end
  
  def loadAllResultFiles(task_folder)
    results = []
        
    if File.exists?("#{task_folder}/seman_prior.txt") #Load result from one prediction method
      resultArray = loadResultFile(task_folder,"seman_prior.txt")
      resultArray.collect! {|result| result.chomp }   #Get rid of line breakers
      results.push Hash["Semantic Prior Network",resultArray] #Save results into hash value, key equals method name
    end
    
    if File.exists?("#{task_folder}/seman_nprior.txt")
      resultArray = loadResultFile(task_folder,"seman_nprior.txt")
      resultArray.collect! {|result| result.chomp }
      results.push Hash["Semantic Non-Prior Network",resultArray]
    end
    
    if File.exists?("#{task_folder}/ppi_prior.txt")
      resultArray = loadResultFile(task_folder,"ppi_prior.txt")
      resultArray.collect! {|result| result.chomp }
      results.push Hash["PPI Prior Network",resultArray]
    end
        
    if File.exists?("#{task_folder}/ppi_nprior.txt")
      resultArray = loadResultFile(task_folder,"ppi_nprior.txt")
      resultArray.collect! {|result| result.chomp }
      results.push Hash["PPI Non-Prior Network",resultArray]
    end
    
    return results
  end
  
  def loadResultFile(task_folder, file_name)
    resultArray = []
    f = File.open("#{task_folder}/#{file_name}") or die "Unable to open file..."
    f.each_line do |line|
       resultArray.push line
    end
    resultArray.collect! {|result| result.chomp } #Get rid of line breakers
  end
  
  def writeOverlappedResultsFile(task_folder)   #Compare all result files and generate overlapped result file
    results = []
    
    if File.exists?("#{task_folder}/seman_prior.txt")
      seman_prior = loadResultFile(task_folder,"seman_prior.txt")
      unless seman_prior.empty?
        results.push(seman_prior) #Put all results into the array
      end
    end
    
    if File.exists?("#{task_folder}/seman_nprior.txt")
      seman_nprior = loadResultFile(task_folder,"seman_nprior.txt")
      unless seman_nprior.empty?
        results.push(seman_nprior)
      end
    end
    
    if File.exists?("#{task_folder}/ppi_prior.txt")
      ppi_prior = loadResultFile(task_folder,"ppi_prior.txt")
      unless ppi_prior.empty?
        results.push(ppi_prior)
      end
    end
        
    if File.exists?("#{task_folder}/ppi_nprior.txt")
      ppi_nprior = loadResultFile(task_folder,"ppi_nprior.txt")
      unless ppi_nprior.empty?
        results.push(ppi_nprior)
      end
    end
    
    #Remove overlapped results
    overlappedResults = results[0]
    
    results.each do |resultArray|
      overlappedResults = resultArray & overlappedResults #Only non-overlapped resultArrya will be push into the result array
    end
    
    File.open("#{task_folder}/overlapped.txt", "w", :type => 'text/html; charset=utf-8'){ |f| f << overlappedResults.join("\n")}
  end

  def generateZipFile(task_id)
    task_folder = Rails.root.join('task_temp',task_id)
    zipfile_name = "#{task_folder}/#{task_id}.zip"
    if File.exists?(zipfile_name)
      File.delete(zipfile_name)
    end
    
    result_files = Dir.entries(task_folder)
    Zip::ZipFile.open(zipfile_name, Zip::ZipFile::CREATE) do |zipfile|  #Use Zip::Zipfile gem to zip the folder
      result_files.each do |filename|
        unless filename == "." || filename == ".."
          zipfile.add(filename, "#{task_folder}/#{filename}")
        end
      end
    end
    return zipfile_name
  end

  def getLinkageInterval(omim_id)
    #Analyze linkage interval information from OMIM API
    information_url = "#{OMIM_API_URL}?mimNumber=#{omim_id}&apiKey=#{OMIM_API_KEY}&#{OMIM_INCLUDED_SECTIONS}"
    #Put the omim entry into XML object
    information_xml = Nokogiri::XML(open(information_url))
    information_to_be_parsed = information_xml.xpath("////textSectionContent").to_s
    linkage_interval = parse_linkage_interval(information_to_be_parsed) #Parse linkage interval out from free text
  end
  
  def parse_linkage_interval(information) #Find linkage interval using regex from free text
    linkage_interval = []
    #Use rubular.com for verification
    interval_pattern1 = /t\((((\d+|X|Y);*)+)\)\((((\d+|X|Y)*(p|q)(\d+)(\.\d+)*;*)+)\)/ #e.g. t(2;12;X)(q22.3;12q22;q21.33)
    interval_pattern2 = /((\d+|X|Y)(p|q)(\d+)(\.\d)*(-(p|q)(\d+)(\.\d)*)*)/ #e.g. 12q11.3-q12
    simple_pattern = /(\d+|X|Y)+((p|q)\d+(\.\d+)*)/ #e.g 12q11.3
    
    information.scan(interval_pattern1).each do |m|
      chromosome = m[0].split(';') #m[0] is the first parentheses
      band = m[3].split(';')  #m[3] is the second parentheses
      interval = chromosome.map.with_index do |elem, idx|
        if band[idx] =~ simple_pattern
          elem + $2 #$2 is the q11.3 part 
        else
          elem + band[idx]
        end
      end  
      linkage_interval.concat(interval)
    end
    
    information.scan(interval_pattern2).each do |m|
      linkage_interval.push(m[0]) #m[0] is the whole match
    end
    
    linkage_interval.uniq!
  end

end

app/helpers/prediction_helper.rb
module PredictionHelper
  
  def enableValidator #Initial clientSideValidation gem to validate the prediction parameter
    return raw "$('#new_prediction').enableClientSideValidations();"
  end

  def resetValidator  #Reset clientSideValidation to original format - needed after each validation process
    return raw "$('#new_prediction').resetClientSideValidations();"
  end
  
  def checkGeneLocation(symbol, linkage_interval, omim_id)
    gene = Gene.find_by_symbol(symbol)
    unless gene.nil?
      gene.diseases.each do |disease| #Check if a gene is already linked to a disease in the database
        if disease.omim_id.to_s == omim_id
          return "gene-known-to-disease"  #Tag for DOM selector, used for jQuery selection
        end
      end      
      
      unless linkage_interval.nil?
        linkage_interval.each do |interval| #Check if the gene is in a linkage interval linked to the disease
          return "gene-in-interval" if gene.in_interval?(interval)  #Tag for DOM selector, used for jQuery selection
        end
      end
    end
    return
  end

end

app/views/predictions/_overlapped_prediction_results.html.erb
<!-- Load the result array and organize it into html -->

<% if @overlapped_results.empty? %> <!-- No prediction result -->
  <div class="vmiddle-major">
    <h3>No Overlapped Result Predicted on All Networks!</h3>	
    <div class="button-area">
      <%= submit_tag "Show All Results", :onclick => "showAllResults()", :class => "go-button smaller"%>
      <%= form_tag( {:controller => 'predictions', :action => 'downloadResults'}, :class => "inline-display", :method => "get" ) do %>
  		<%= text_field_tag "task_id", @task_id, :type => "hidden" %>
  		<%= submit_tag "Download Results", :class => "go-button smaller"%>
  	  <% end %>
    </div>
  </div>
<% else %>
  <%= render 'shared/initial_colorbox' %> <!-- Need pop window if has result -->

  <div class="button-area">
    <%= submit_tag "Show All Results", :onclick => "showAllResults()", :class => "go-button smaller"%>
    <%= form_tag( {:controller => 'predictions', :action => 'downloadResults'}, :class => "inline-display", :method => "get" ) do %>
  		<%= text_field_tag "task_id", @task_id, :type => "hidden" %>
  		<%= submit_tag "Download Results", :class => "go-button smaller"%>
  	<% end %>
	<div class="legend">
  		<div class="green-square">Gene Known to the Disease</div>
  		<div class="red-square">Gene on a Known Linkage Interval</div>
  	</div>
  </div>

  <table class="prediction-rank-table">
    <thead><tr><th>#</th></tr></thead>
    <tbody>
      <% for row_num in 1..@overlapped_results.length %>	<!-- Load result length and add col num -->
        <tr><td><%= row_num %></td></tr>
      <% end %>
    </tbody>
  </table>
  
  <table class="prediction-result-table">
    <thead><tr><th>Overlapped Gene</th></tr></thead>	<!-- Format overlapped results into html code -->
    <tbody>
      <% @overlapped_results.each do |result| %>
        <tr class="<%= checkGeneLocation(result, @linkage_interval, @omim_id) %>"><td>
          <%= link_to result, { :controller => "genes", :action => "search", :symbol => result, :omim_id => @omim_id }, 
	          					:class => "gene-information-colorbox", :title => "Gene Information" %>
        </td></tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/predictions/_parameter_form.html.erb
<%= form_for @prediction, :url => { :action => "predict" }, :method => "get", :validate => true do |f| %>
  
  <%= render 'shared/error_messages'%>
  
  <%=f.text_field :omim_id, :value => @disease.omim_id, :type => "hidden" %>
  <table class="field-table">
	<col /><col /><col />
	<tr>
		<td class="head-label" colspan="3">
			<%= "OMIM Entry: ##{@disease.omim_id}" %>
			<br />
			<%= link_to @disease.disease_name, omim_link(@disease.omim_id), :target => "_blank" %>
		</td>
	</tr>
	
	<tr>
  		<td class="label"><%= f.label :top_results, "Show Top Result # " %></td>
  		<td class="input" colspan="2"><%= f.text_field :top_results, :value => "100", :onclick => enableValidator %></td>
  	</tr>
  	
  	<tr>
  		<td class="label">
  			<%= f.label :gamma, "Restart Probability (γ) " %> 
  			<%= image_tag("infoButton.png", :size => "24x24", :class => "field-infobutton", :data => { :url => tips_gamma_path }) %>
		</td>
  		<td class="input" colspan="2"><%= f.text_field :gamma, :value => "0.7", :onclick => enableValidator %></td>
  	</tr>
  	
  	<tr>
  		<td class="label">
  			<%= f.label :lambda, "Jumping Probability (λ) " %> 
  			<%= image_tag("infoButton.png", :size => "24x24", :class => "field-infobutton", :data => { :url => tips_lambda_path }) %>
  		</td>
  		<td class="input" colspan="2"><%= f.text_field :lambda, :value=> "0.5", :onclick => enableValidator %></td>
  	</tr>
  	
  	<tr>
  		<td class="label">
  			<%= f.label :eta, "Sub-network weight (η) " %>
  			<%= image_tag("infoButton.png", :size => "24x24", :class => "field-infobutton", :data => { :url => tips_eta_path }) %>
  		</td>
  		<td class="input" colspan="2"><%= f.text_field :eta, :value => "0.5", :onclick => enableValidator %></td>
  	</tr>
  	
  	<tr>
  		<td class="label" rowspan="4">
  			<%= f.label :network, "Network Selection " %><br />
  			<%= image_tag("infoButton.png", :size => "24x24", :class => "field-infobutton", :data => { :url => tips_net_selection_path }) %>
  		</td>
  		
		<td class="label"><%= label_tag "semantic_prior", "HGS-Prior " %></td>
  		<td class="input"><%= f.check_box "network", {:multiple => true, :checked => true}, "getSemanPrior", nil %></td>
  	</tr>
  	
  	<tr>
  		<td class="label"><%= label_tag "semantic_nprior", "HGS-NonPrior " %></td>
		<td class="input"><%= f.check_box "network", {:multiple => true, :checked => true}, "getSemanNPrior", nil %></td>
  	</tr>
  	<tr>
  		<td class="label"><%= label_tag "ppi_prior", "PPI-Prior " %></td>
		<td class="input"><%= f.check_box "network", {:multiple => true, :checked => true}, "getPPIPrior", nil %></td>
  	</tr>
  	<tr>
  		<td class="label"><%= label_tag "ppi_nprior", "PPI-NonPrior " %></td>
  		<td class="input"><%= f.check_box "network", {:multiple => true, :checked => true}, "getPPINPrior", nil %></td>
  	</tr>
  	
  	<tr>
  		<td class="submit" colspan="3">
  			<%= f.submit "Reset",  :type => "reset", :class => "go-button", :onclick => resetValidator,  :id => 'reset' %>
  			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
  			<%= f.submit "Start!", :class => "go-button"%>
  		</td>
  	</tr>

  </table>
<% end %>

app/views/predictions/_prediction_results.html.erb
<!-- This section loads the length of result lists from different method and decide the length of the result table-->
<!-- A method may not have a result or have less results then the others, check in the if statement -->
<% 
max_result_num = 0
array_nums = 0
failed_prediction_messages = []
@results.each do |resultHash|
	resultHash.each do |network, resultArray|
		if resultArray.empty?
			failed_prediction_messages.push("Failed to predict phenotype-genotype relationship on #{network}")
		else
			array_nums += 1
			result_num = resultArray.length
			if result_num > max_result_num
				max_result_num = result_num
			end
		end
	end
end
%>

<!-- Colorbox initialed here, enable pop window -->
<%= render 'shared/initial_colorbox' %>

<% unless failed_prediction_messages.empty? %>
  <div class="failed_prediction_message">
  	<ul>
    <% failed_prediction_messages.each do |message| %>
    	<li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<% if array_nums > 1 %>
  <div class="button-area">
	<%= submit_tag "Show Overlapped Results", :onclick => "showOverlappedResults()", :class => "go-button smaller"%>
	<%= form_tag( {:controller => 'predictions', :action => 'downloadResults'}, :class => "inline-display", :method => "get" ) do %>
  		<%= text_field_tag "task_id", @task_id, :type => "hidden" %>
  		<%= submit_tag "Download Results", :class => "go-button smaller"%>
  	<% end %>
  	<div class="legend">
  		<div class="green-square">Gene Known to the Disease</div>
  		<div class="red-square">Gene on a Known Linkage Interval</div>
  	</div>
  </div>
<% elsif array_nums == 1 %>
	<div class="button-area">
	<%= form_tag( {:controller => 'predictions', :action => 'downloadResults'}, :class => "inline-display", :method => "get" ) do %>
  		<%= text_field_tag "task_id", @task_id, :type => "hidden" %>
  		<%= submit_tag "Download Results", :class => "go-button smaller"%>
  	<% end %>
  	<div class="legend">
  		<div class="green-square">Gene Known to the Disease</div>
  		<div class="red-square">Gene on a Known Linkage Interval</div>
  	</div>
  </div>
<% end %>

<table class="prediction-rank-table">
  <thead><tr><th>Rank</th></tr></thead>
  <tbody>
	<% for row_num in 1..max_result_num %>
	  <tr><td><%= row_num %></td></tr>
	<% end %>
  </tbody>
</table>
<% @results.each do |resultHash| %>
  <% resultHash.each do |network, resultArray| %>
  	<% unless resultArray.empty? %>
  	  <table class="prediction-result-table">
	    <thead><tr><th><%= network %></th></tr></thead>
	    <tbody>
	      <% resultArray.each do |result| %>
	      
	        <!-- Check the gene's location see if it requires special display -->
	        <tr class="<%= checkGeneLocation(result, @linkage_interval, @omim_id) %>"><td>
	        	
	          <%= link_to result, { :controller => "genes", :action => "search", :symbol => result, :omim_id => @omim_id }, 
	          						:class => "gene-information-colorbox", :title => "Gene Information" %>
	        </td></tr>
	      <% end %>
	    </tbody>
	  </table>
	<% end %>
  <% end %>
<% end %>

app/views/predictions/parameter.html.erb
<%= stylesheet_link_tag "application", :media => "all" %>

<div class="parameter-panel">
<h3>
	Predict with Random Walk with Restart Algorithm
	<%= link_to image_tag("infoButton.png", :size => "24x24", 
											:class => "field-infobutton", 
											:data => { :url => tips_rwrh_path }),
											"http://bioinformatics.oxfordjournals.org/content/26/9/1219.short",
											:target => "_blank" %>
	<!-- The data path is auto constructed by rails -->
</h3>

<%= render 'parameter_form'%>

<%= render 'shared/enableTipScript'%>	<!--The page has info button, requiring qtip-->

</div>

app/views/predictions/pollAllResult.js.erb
<% unless @results.nil? %>
$("#loading").remove();
$("#prediction-results").empty();
$("#prediction-results").attr( "data-result", "true" );
$("#prediction-results").append("<h2>Prediction Results</h2>");
$("#prediction-results").append("<%=raw escape_javascript(render 'prediction_results', :collection => @results) %>");
<% end %>

app/views/predictions/pollAllResults.js.erb
<!-- Load all results chunk into the page -->
<% unless @results.nil? %>
	$("#loading").remove();
	$("#prediction-results").empty();
	$("#prediction-results").attr( "data-result", "true" );
	$("#prediction-results").append("<h2>Prediction Results For</h2>");
	$("#prediction-results").append(
  		"<h4 style=\"margin-top: -15px;\"><a href=\"<%= "http://www.omim.org/entry/#{@disease.omim_id}" %>\" target=\"_blank\"><%= @disease.disease_name %></a></h4>");
	$("#all-results").append("<%=raw escape_javascript(render 'prediction_results', :collection => @results) %>");
<% end %>

<!-- Load overlapped results chunk into the page, but hidden at the first place -->
<% unless @overlapped_results.nil? %>
	$("#overlapped-results").append("<%=raw escape_javascript(render 'overlapped_prediction_results', :collection => @overlapped_results) %>");
	$("#overlapped-results").hide();
<% end %>

app/views/predictions/pollResult.js.erb
<% unless @results.nil? %>
$("#loading").remove();
$("#prediction-results").attr( "data-result", "true" )
$("#prediction-results").append("<h2>Prediction Results</h2>");
$("#prediction-results").append("<%=raw escape_javascript(render 'prediction_results', :collection => @results) %>");
<% end %>

app/views/predictions/predict.html.erb
<div class="loading-panel vmiddle-major" id="loading">
<%= image_tag("loading.gif", :class => "loading") %>
<%= image_tag("loading-hint.gif", :class => "loading") %>
</div>

<div id="prediction-results" data-task-id="<%= @task_id %>" data-omim-id="<%= @omim_id %>"></div>
<div id="all-results"></div>
<div id="overlapped-results"></div>

app/views/predictions/showAllResults.js.erb
$("#overlapped-results").hide();
$("#all-results").show();

app/views/predictions/showOverlappedResults.js.erb
$("#all-results").hide();
$("#overlapped-results").show();