config/routes.rb
MEbGDP::Application.routes.draw do

  get "tips/rwrh"
  get "tips/gamma"
  get "tips/lambda"
  get "tips/eta"
  get "tips/net_selection"
  get "tips/phenome_net"

  get "predictions/parameter"
  get "predictions/predict"
  get "predictions/pollAllResults"
  get "predictions/showOverlappedResults"
  get "predictions/showAllResults"
  get "predictions/downloadResults"

  get "diseases/search"
  
  get "genes/search"
  get "genes/compare_phenotype"

  root :to => 'pages#home'
  match '/about', :to => 'pages#about'
  match '/contact', :to => 'pages#contact'
  match '/help', :to => 'pages#help'
  
  get 'pages/autocomplete_disease_disease_name'

end

app/controllers/diseases_controller.rb
class DiseasesController < ApplicationController
  def search #Search Disease by OMIM_ID or Disease Name
    @diseases = Disease.where("omim_id LIKE :keyword OR disease_name LIKE :keyword", 
                              { :keyword => "%#{params[:keyword]}%" })
                       .paginate(:page => params[:page], :per_page => 20)  #Paginate to 20 results/page
    @keyword = ""  #Reset keyword
    @title = "Search Result"
  end
end

app/helpers/diseases_helper.rb
module DiseasesHelper
  def omim_link(omim_id)  #Generate omim entry link from omim id
    "http://www.omim.org/entry/" + omim_id.to_s
  end
end

app/views/diseases/_disease_search_form.html.erb
<!--Used for Disease search box-->
<%= form_for @keyword, :url => url_for(:controller => 'diseases', :action => 'search'), :method => 'get' do |f| %>  
  <%=f.autocomplete_field :keyword, pages_autocomplete_disease_disease_name_path,
                          :class => "text round disease-search", 
                          :value => "Enter an OMIM # or disease name to start",
                          :onclick => "$('#_keyword').get(0).value=''" %> 
  <%= f.submit "Go!", :class => "go-button" %>
<% end %>

app/views/diseases/_no_search_result.html.erb
<!--No search result, retrieve the search box again-->
<div class="vmiddle-major">
	<h4>No OMIM entry matches your search term, please try another one.</h4><br />
	<%= render 'diseases/disease_search_form'%>
</div>

app/views/diseases/_search_result.html.erb
<%= will_paginate @diseases, :class => 'flickr_pagination' %>
<!--Need paginate the results-->
<br />

<table class="result">
	<thead>
		<tr>
			<th>OMIM ID</th>
			<th>Disease Name</th>
			<th>OMIM Entry</th>
			<th>Prediction</th>
		</tr>
	</thead>
	<tbody>
		<% @diseases.each do |disease| %>
			<tr>
				<td><%= disease.omim_id %></td>
				<td><%= disease.disease_name %></td>
				<td>
					<%= link_to "OMIM Entry", omim_link(disease.omim_id), :target => "_blank" %>
				</td>
				<td>
					<%= link_to "Start Prediction", { :controller => "predictions", 
													:action => "parameter", 
													:omim_id => disease.omim_id }, 
													:class => 'parameter-panel-colorbox',
													:title => 'Set Parameter' %>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>
<br />
<%= will_paginate @diseases, :class => 'flickr_pagination' %>
<br />
<%= link_to "Start a new search", root_path %>

app/views/diseases/search.html.erb
<!-- Search Result Layout page -->
<h2>Search Results</h2>

<% if @diseases.empty? %>
	<%= render 'no_search_result' %>
<% else %>
	<%= render 'shared/initial_colorbox' %>
	<%= render 'search_result' %>
<% end %>