config/routes.rb
MEbGDP::Application.routes.draw do

  get "tips/rwrh"
  get "tips/gamma"
  get "tips/lambda"
  get "tips/eta"
  get "tips/net_selection"
  get "tips/phenome_net"

  get "predictions/parameter"
  get "predictions/predict"
  get "predictions/pollAllResults"
  get "predictions/showOverlappedResults"
  get "predictions/showAllResults"
  get "predictions/downloadResults"

  get "diseases/search"
  
  get "genes/search"
  get "genes/compare_phenotype"

  root :to => 'pages#home'
  match '/about', :to => 'pages#about'
  match '/contact', :to => 'pages#contact'
  match '/help', :to => 'pages#help'
  
  get 'pages/autocomplete_disease_disease_name'

end

app/views/layouts/_footer.html.erb
<div class="copyright">
© 2013, Xiaoli Wu <br />
<%= link_to "xiaoliwu@jhmi.edu", "mailto:xiaoliwu@jhmi.edu"%> <br />
<%= link_to "Division of Health Science Informatics", "http://dhsi.med.jhmi.edu", :target => '_blank' %>, 
<%= link_to "Johns Hopkins University School of Medicine", "http://www.hopkinsmedicine.org/", :target => '_blank' %><br />
</div>

app/views/layouts/_header.html.erb
<%= render 'shared/initial_colorbox' %>

<div class="menu">
<ul>
	<li><%= link_to "Home", root_path %></li>
	<li><%= link_to "Help", help_path, :class => "general-colorbox", :title => "Help" %></li>
	<li><%= link_to "About", about_path, :class => "general-colorbox", :title => "About" %></li>
	<li><%= link_to "Contact", contact_path, :class => "general-colorbox", :title => "Contact" %></li>
</ul>
</div>

app/views/layouts/_link_out.html.erb
<table class="image-link" align="center"><tr>
	<td>
		<%= link_to image_tag('dhsi-logo.png', :size => "120x61"), 'http://dhsi.med.jhmi.edu/', :target => '_blank' %>
	</td>
	<td>
		<%= link_to image_tag('jhmi-logo.gif', :size => "120x80"), 'http://www.hopkinsmedicine.org/', :target => '_blank' %>
	</td>
</tr></table>

app/views/layouts/_script.html.erb
<!-- JQuery and jquery dependent scripts -->
<%= javascript_include_tag 'jquery-1.8.0.min.js', 'jquery-ui-1.8.24.custom.min.js', 'autocomplete-rails.js', 'rails.js'  %>

<%= javascript_include_tag "application" %>

<!-- Qtip script, for info button -->
<%= javascript_include_tag "jquery.qtip.js" %>

<!-- ClientSide Validation -->
<%= javascript_include_tag "rails.validations.js" %>

<!-- Colorbox for pop window -->
<%= javascript_include_tag "jquery.colorbox.js"%>
<!--[if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_stylesheet.html.erb
<!-- Main style library, watch out for all its default effects -->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'jquery-ui-1.8.24.custom.css' %>
<%= stylesheet_link_tag "application", :media => "all" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
  	<% if @title.blank?%>	<!-- HTML Title -->
  		MEbGDP
  	<% else %>
  		MEbGDP | <%= @title %>
  	<% end %>
  </title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= render 'layouts/script' %>	<!-- Necessary scripts -->
  <%= render 'layouts/stylesheet' %> <!-- Necessary styles -->
  <%= csrf_meta_tags %>
</head>
<body>
 <header>
 	<%= render 'layouts/header' %>
 </header>
	
 <section>
 	 <div class="major">
  	 	<%= yield %>
  	 </div>
 </section>
   
  <footer>
  	<%= render 'layouts/footer' %>
  </footer>

</body>
</html>

app/views/layouts/noLayout.html.erb
<%= render 'layouts/stylesheet' %>

<body>
	<%= yield %>	<!-- This is an empty page layout, for those does need headers/footers -->
</body>